# --- ФОН ---
background {
    monitor =
    path = Pictures/Wallpapers/Linux_abstract.png
}

# --- ПОЛЕ ВВОДА ПАРОЛЯ ---
input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_size = 0.33
    dots_spacing = 0.15
    
    # Цвета TokyoNight
    outer_color = rgb(7a, a2, f7)     # Синяя обводка
    inner_color = rgb(1a, 1b, 26)     # Темный фон внутри
    font_color = rgb(c0, ca, f5)      # Цвет точек пароля
    check_color = rgb(bb, 9a, f7)     
    fail_color = rgb(f7, 76, 8e)     

    fade_on_empty = false
    placeholder_text = <i>Password...</i>
    
    position = 0, 20
    halign = center
    valign = bottom
}

# --- ЧАСЫ (Большие и красивые) ---
label {
    monitor =
    text = $TIME
    font_size = 64
    font_family = MesloLGS Nerd Font Bold
    color = rgb(c0, ca, f5)           # Светло-синий текст
    
    position = 0, -20
    halign = center
    valign = top
}
